name: Build and Release Chrome Extension

on:
  push:
    branches:
      - main
      - build

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: v${{ github.run_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create private key file
        run: echo "${{ secrets.PRIVATE_KEY }}" > private.pem

      - name: Pack Chrome Extension
        run: npx crx3 pack browser-extension -p private.pem

      - name: Rename and Zip CRX
        run: |
          mv web-extension.crx hellyes-chrome.crx
          zip hellyes-chrome.zip hellyes-chrome.crx

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload CRX as Zip to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: "hellyes-chrome.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}